### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by feinmann** [schochastics/modern2-cv#1]
Hi there, I had some trouble with my TexLive setup and tried a bit around. In the end I used tinytex and I get also pretty beautiful PDFs, thanks for that.

But I cannot get the font-options to work. I always get the same font. I even tried to change some commands in the template.tex file, but nothing seems to have any effect.

Do you know, how to debug this? Help is very much appreciated, as are your beautiful templates!
Thanks

**Comment by schochastics** [comment]
Thanks for this. I had a similar experience and if I recall correctly, the only way for me was to set the `pdf-engine` option to `pdflatex`.  Let me know if that has an effect for you!

**Comment by feinmann** [comment]
So I added `pdf-engine: pdflatex` to `cv.qmd` and it works:

> pandoc 
>   to: latex
>   output-file: cv.tex
>   template: _extensions/schochastics/modern2-cv/template.tex
>   standalone: true
>   pdf-engine: pdflatex
>   variables:
>     graphics: true
>     tables: true
>   default-image-extension: pdf

The produced pdfs are slightly larger, in terms of KBs (~150 KB vs ~80 KB), but still, the fonts are all the same, so are the filesizes. No matter what font I set through `cvfont`.

Any other ideas on that? Thanks a lot!

**Comment by feinmann** [comment]
Ok, I am making progress here: looking up some advice here https://tug.org/FontCatalogue/firasans/ (since I want to use that font) under *usage*, I changed (in `template.tex`)

`\usepackage[default]{$cvfont$}` to

`\usepackage[sfdefault]{$cvfont$}`

and deleted 

`\renewcommand*\familydefault{\sfdefault}` ...

And for my peticular font, it works :) 

And works also for `raleway` and `gillius`... but other fonts have problem with the option `sfdefault` (such as `comfortaa`) 

Does this make sense for you?

**Comment by schochastics** [comment]
nope, but that just sounds like "normal" latex things. I think I will need to work on the font support in the future

**Comment by feinmann** [comment]
Thanks for your efforts! Will close this :)
