### ISSUE TITLE
CV with no image

### ISSUE THREAD

**Issue by tomasruizt** [schochastics/modern2-cv#4]
Hi! 
Great work on the template. I'm using it for my CV now. I wanted to know if it is possible to leave out the picture, because in the anglosphere the picture might actually be very rare. I tried removing the `image: ...` line of code, but that raised a compilation error. I also tried using a 1 pixel image, but the blank space is still noticeable in the final CV. Do you know of any simple solution to leave the picture out?
Best,

**Comment by schochastics** [comment]
@tomasruizt I made 
```yaml
sidebar:
   image: portrait.png
```
optional. So just remove the line `image: portrait.png` (or whatever the image is called).

You just need to update the extension :)

**Comment by tomasruizt** [comment]
@schochastics It works perfectly! Absolute legend 🚀
